// shared-core/src/components/Skeletons/SkeletonShimmer/SkeletonShimmer.tsx
import type { JSX } from "react";
import type { SkeletonShimmerProps } from "@shared-core/types/props";

import "@shared-core/components/Skeletons/SkeletonShimmer/SkeletonShimmer.css";

const SkeletonShimmer = ({ rounded, className }: SkeletonShimmerProps): JSX.Element => {
  const classes = ["skeleton-shimmer", rounded && "skeleton-shimmer--rounded", className]
    .filter(Boolean)
    .join(" ");

  return <div className={classes}></div>;
};

export default SkeletonShimmer;

// product-detail/src/components/SkeletonShimmer/SkeletonShimmer.vue
<script setup lang="ts">
import "@shared-core/components/Skeletons/SkeletonShimmer/SkeletonShimmer.css";

defineProps<{
  rounded?: boolean;
  loadingClass?: string;
}>();
</script>

<template>
  <div :class="['skeleton-shimmer', rounded && 'skeleton-shimmer--rounded', loadingClass]" />
</template>
