// shared_angular/src/app/components/core/forms/form-search/form-search.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnDestroy,
  ViewChild,
} from "@angular/core";

import template from "@src/app/components/core/forms/form-search/form-search.component.html";
import styles from "@src/app/components/core/forms/form-search/form-search.component.css";

import { mountComponent, unMountComponent } from "shared_core/SharedCore";
import { Component as ComponentSharedCore } from "shared_core/SharedCoreEnums";
import { FormSearchProps } from "shared_core/SharedCoreProps";
import { MountOptions } from "shared_core/SharedCoreEntities";

@Component({
  selector: "app-form-search",
  template: template,
  styles: [styles],
})
export class FormSearchComponent implements AfterViewInit, OnDestroy {
  @ViewChild("formsearch") ref: ElementRef | null = null;

  @Input() idRoot: FormSearchProps["idRoot"] = "";
  @Input() placeholder: FormSearchProps["placeholder"] = "";
  @Input() language: FormSearchProps["language"] = "en";
  @Input() className: FormSearchProps["className"] = "";
  @Input() classNameWrapper: FormSearchProps["classNameWrapper"] = "";
  @Input() formSubmit: FormSearchProps["onSubmit"] =
    this.onDefalutSubmit.bind(this);

  private componentName: string = "app-form-search";

  ngAfterViewInit(): void {
    const options: MountOptions = {
      idComponent: ComponentSharedCore.FormSearch,
      props: {
        idRoot: this.idRoot,
        placeholder: this.placeholder,
        language: this.language,
        className: this.className,
        onSubmit: this.formSubmit,
      },
    };

    mountComponent(this.ref!.nativeElement, options);
  }

  ngOnDestroy(): void {
    unMountComponent(this.idRoot);
  }

  viewProps(): void {
    console.log(`Props of ${this.componentName}:
      - ref: ${this.ref}
      - idRoot: ${this.idRoot}
      - placeholder: ${this.placeholder}
      - language: ${this.language}
      - className: ${this.className}
      - classNameWrapper: ${this.classNameWrapper}
      - onSubmit: ${this.formSubmit}
    `);
  }

  // Defaults Fns
  onDefalutSubmit(inputValue: string) {
    console.log(
      "Executed in shared_angular - onDefaultSubmit: ",
      this.componentName,
      inputValue
    );
  }
}

<div #formsearch [ngClass]="classNameWrapper"></div>

// container/src/components/core/Forms/FormSearch/FormSearch.tsx
import React, { useEffect, useRef } from "react";

import { mountComponent, unMountComponent } from "shared_core/SharedCore";
import { FormSearchProps } from "shared_core/SharedCoreProps";
import { Component } from "shared_core/SharedCoreEnums";
import { MountOptions } from "shared_core/SharedCoreEntities";

export const FormSearch = ({
  idRoot,
  placeholder,
  className,
  classNameWrapper,
  children,
  onSubmit,
}: FormSearchProps) => {
  const ref = useRef<HTMLDivElement | null>(null);

  const onInit = () => {
    const options: MountOptions = {
      idComponent: Component.FormSearch,
      props: {
        idRoot: idRoot,
        placeholder: placeholder,
        className: className,
        children: children,
        onSubmit: onSubmit,
      },
    };

    mountComponent(ref.current!, options);
  };

  const onDestroy = () => {
    unMountComponent(idRoot);
  };

  useEffect(() => {
    onInit();

    return () => {
      onDestroy();
    };
  }, []);

  return <div ref={ref} className={classNameWrapper}></div>;
};
