// shared-react/src/components/SharedMfe/SharedMfe.tsx
import { Suspense } from "react";
import { SkeletonShimmer } from "shared-core/sdk";

import type { JSX } from "react";
import type { SharedMfeProps } from "@shared-react/types/props";

const SharedMfe = <P extends object>({
  component: Component,
  componentProps,
  wrapperClass,
  loadingClass,
}: SharedMfeProps<P>): JSX.Element => {
  const rawClassName = (componentProps as { className?: unknown }).className;
  const inferredWrapperClass =
    typeof rawClassName === "string" && rawClassName ? `${rawClassName}-wrapper` : undefined;
  const resolvedWrapperClass = wrapperClass ?? inferredWrapperClass;

  return (
    <div data-mfe="shared-core" className={resolvedWrapperClass}>
      <Suspense fallback={<SkeletonShimmer className={loadingClass!} />}>
        <Component {...componentProps} />
      </Suspense>
    </div>
  );
};

export default SharedMfe;

// product-detail/src/components/SharedMfe/SharedMfe.vue
<script setup lang="ts" generic="P extends object">
import { ref, onErrorCaptured } from "vue";

import type { SharedMfeProps } from "@product-detail/types/props";

import SkeletonShimmer from "@product-detail/components/SkeletonShimmer/SkeletonShimmer.vue";
import SharedMfeMount from "@product-detail/components/SharedMfe/SharedMfeMount.vue";

const props = defineProps<SharedMfeProps<P>>();

const failed = ref(false);

onErrorCaptured((err): boolean => {
  console.error("[Shared MFE Load Error]", err);
  failed.value = true;
  return false;
});
</script>

<template>
  <Suspense v-if="!failed">
    <SharedMfeMount
      :loader="props.loader"
      :component-props="props.componentProps"
      :wrapper-class="props.wrapperClass!"
      :mfe="props.mfe!"
    />
    <template #fallback>
      <SkeletonShimmer :loading-class="props.loadingClass!" />
    </template>
  </Suspense>
</template>
