// shared_angular/src/app/components/buttons/button-white/button-white.component.ts
import { Component, Input, OnInit } from "@angular/core";

import { ButtonWhiteProps } from "@src/app/entities/props";

import template from "@src/app/components/buttons/button-white/button-white.component.html";
import styles from "@src/app/components/buttons/button-white/button-white.component.css";

@Component({
  selector: "app-button-white",
  template: template,
  styles: [styles],
})
export class ButtonWhiteComponent implements OnInit {
  @Input() rounded: ButtonWhiteProps["rounded"] = false;
  @Input() borderGray: ButtonWhiteProps["borderGray"] = false;
  @Input() ariaLabel: ButtonWhiteProps["ariaLabel"] = "";
  @Input() className: ButtonWhiteProps["className"] = "";

  @Input() onClick: ButtonWhiteProps["onClick"] =
    this.onDefaultClick.bind(this);

  private componentName: string = "app-button-white";

  ngOnInit(): void {
    // this.viewProps();
  }

  viewProps(): void {
    console.log(`Props of ${this.componentName}:
      - rounded: ${this.rounded}
      - borderGray: ${this.borderGray}
      - ariaLabel: ${this.ariaLabel}
      - className: ${this.className}
      - onClick: ${this.onClick}`);
  }

  // Defaults Fns

  onDefaultClick(e: MouseEvent): void {
    console.log("Executed in shared_angular - Click: ", this.componentName, e);
  }
}

<button
  type="button"
  class="button-white"
  [ngClass]="[
    'button-white',
    rounded ? 'button-white--rounded' : '',
    borderGray ? 'button-white--border-gray' : '',
    className
  ]"
  [attr.aria-label]="ariaLabel"
  (click)="onClick($event)"
>
  <ng-content></ng-content>
</button>

// shared_core/src/components/Buttons/ButtonWhite/ButtonWhite.tsx
import React from "react";

import { ButtonWhiteProps } from "@src/entities/props";

import "@src/components/Buttons/ButtonWhite/ButtonWhite.css";

export const ButtonWhite = ({
  ariaLabel,
  borderGray,
  rounded,
  type,
  children,
  className,
  html,
  onClick,
}: ButtonWhiteProps) => {
  if (html)
    return (
      <button
        type={type ?? "button"}
        className={`button-white ${rounded && "button-white--rounded"} ${
          borderGray && "button-white--border-gray"
        } ${className}`}
        aria-label={ariaLabel}
        onClick={onClick ?? undefined}
        dangerouslySetInnerHTML={{ __html: html }}
      ></button>
    );

  return (
    <button
      type={type ?? "button"}
      className={`button-white ${rounded && "button-white--rounded"} ${
        borderGray && "button-white--border-gray"
      } ${className}`}
      aria-label={ariaLabel}
      onClick={onClick ?? undefined}
    >
      {children}
    </button>
  );
};
