// product_detail/src/components/core/Buttons/ButtonBlack/ButtonBlack.vue
<script setup lang="ts">
import {
    defineProps, ref, onMounted, onBeforeUnmount, watch,
    useSlots, h, render
} from "vue";

import { mountComponent, unMountComponent } from "shared_core/SharedCore";
import { Component } from "shared_core/SharedCoreEnums";
import type { ButtonBlackProps } from "shared_core/SharedCoreProps";
import { MountOptions } from "shared_core/SharedCoreEntities";

const props = defineProps<ButtonBlackProps>();
const slots = useSlots();

const containerRef = ref<HTMLDivElement | null>(null);


function buildChildrenText(): string {
    const host = document.createElement("div");
    const Render = { render: () => slots.default?.() };
    render(h(Render), host);
    const text = host.textContent ?? "";
    render(null, host);
    return text.trim();
}

function init() {
    if (!containerRef.value) return;
    const childrenText = buildChildrenText();

    const options: MountOptions = {
        idComponent: Component.ButtonBlack,
        props: {
            idRoot: props.idRoot,
            ariaLabel: props.ariaLabel,
            rounded: props.rounded,
            children: childrenText,
            language: props.language,
            className: props.className,
            onClick: props.onClick,
        },
    };

    mountComponent(containerRef.value, options);
}
function destroy() { unMountComponent(props.idRoot); }

onMounted(init);
onBeforeUnmount(destroy);

watch(
    () => [props.idRoot, props.language, props.className, props.onClick, props.rounded, props.ariaLabel, slots.default?.()],
    () => { init(); },
    { deep: true }
);
</script>

<template>
    <div ref="containerRef" :class="props.classNameWrapper">
        <slot />
    </div>
</template>

// container/src/components/core/Buttons/ButtonBlack/ButtonBlack.tsx
import React, { useEffect, useRef } from "react";

import { mountComponent, unMountComponent } from "shared_core/SharedCore";
import { ButtonBlackProps } from "shared_core/SharedCoreProps";
import { Component } from "shared_core/SharedCoreEnums";
import { MountOptions } from "shared_core/SharedCoreEntities";

export const ButtonBlack = ({
  idRoot,
  ariaLabel,
  rounded,
  className,
  classNameWrapper,
  children,
  onClick,
}: ButtonBlackProps) => {
  const ref = useRef<HTMLDivElement | null>(null);

  const onInit = () => {
    const options: MountOptions = {
      idComponent: Component.ButtonBlack,
      props: {
        idRoot: idRoot,
        ariaLabel: ariaLabel,
        rounded: rounded,
        className: className,
        children: children,
        onClick: onClick,
      },
    };

    mountComponent(ref.current!, options);
  };

  const onDestroy = () => {
    unMountComponent(idRoot);
  };

  useEffect(() => {
    onInit();

    return () => {
      onDestroy();
    };
  }, []);

  return <div ref={ref} className={classNameWrapper}></div>;
};
