// product-detail/src/components/SharedMfe/SharedMfeMount.vue
<script setup lang="ts" generic="P extends object">
import { ref, computed, onMounted, onBeforeUnmount, inject, watch } from "vue";

import type { MfeCallbacks } from "shared-core/sdk";
import type { SharedMfeProps } from "@product-detail/types/props";

const props = defineProps<SharedMfeProps<P>>();

const containerRef = ref<HTMLDivElement | null>(null);
const callbacks = inject<MfeCallbacks | undefined>("mfeCallbacks", undefined);

const wrapperClass = computed<string | undefined>(() => {
  if (props.wrapperClass) return props.wrapperClass;

  const className = (props.componentProps as { className?: unknown }).className;
  return typeof className === "string" && className ? `${className}-wrapper` : undefined;
});

const mod = await props.loader();

const mountInto = (el: HTMLDivElement): void => {
  mod.mount(el, props.componentProps, {
    ...(callbacks ? { callbacks } : {}),
    ...(props.mfe ? { dataset: { mfe: props.mfe } } : {}),
  });
};

onMounted(() => {
  const el = containerRef.value;
  if (!el) return;

  mountInto(el);
});

watch(
  () => props.componentProps,
  () => {
    const el = containerRef.value;
    if (!el) return;

    mountInto(el);
  }
);

onBeforeUnmount(() => {
  const el = containerRef.value;
  if (!el) return;

  mod.unmount(el);
});
</script>

<template>
  <div ref="containerRef" :class="wrapperClass" />
</template>

// home/src/components/SharedMfe/SharedMfeMount.tsx
import React, { useEffect, useRef, useState } from "react";
import { SkeletonShimmer } from "shared-core/sdk";

import type { JSX } from "react";
import type { SharedComponentModule } from "shared-core/sdk";
import type { SharedMfeMountProps } from "@home/types/props";

const SharedMfeMount = <P extends object>({
  loader,
  componentProps,
  wrapperClass,
  loadingClass,
}: SharedMfeMountProps<P>): JSX.Element => {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    let active = true;
    let mod: SharedComponentModule<P> | null = null;
    const el = containerRef.current;

    loader()
      .then((loaded) => {
        if (!active || !containerRef.current) return;

        mod = loaded;
        mod.mount(containerRef.current, componentProps);
        setMounted(true);
      })
      .catch((error: unknown) => {
        console.error("[Shared MFE Load Error]", error);
      });

    return (): void => {
      active = false;
      if (mod && el) mod.unmount(el);
    };
  }, []);

  return (
    <React.Fragment>
      {!mounted && <SkeletonShimmer className={loadingClass!} />}
      <div ref={containerRef} className={wrapperClass} hidden={!mounted} />
    </React.Fragment>
  );
};

export default SharedMfeMount;
