// product_detail/src/components/core/Galleries/GalleryClothes/GalleryClothes.vue
<script setup lang="ts">
import { defineProps, ref, onMounted, onBeforeUnmount, watch } from "vue";

import { mountComponent, MountOptions, unMountComponent } from "shared_react/SharedReact";
import { GalleryClothesProps } from "shared_react/SharedReactProps";
import { Component } from "shared_react/SharedReactEnums";


const props = defineProps<GalleryClothesProps>();

const containerRef = ref<HTMLDivElement | null>(null);

function init() {
    if (!containerRef.value) return;

    const options: MountOptions = {
        idComponent: Component.GalleryClothes,
        props: {
            idRoot: props.idRoot,
            title: props.title,
            clothes: props.clothes,
            language: props.language,
            className: props.className,
            onClothesClick: props.onClothesClick,
        }
    };


    mountComponent(containerRef.value, options);
}

function destroy() {
    unMountComponent(props.idRoot);
}

onMounted(init);
onBeforeUnmount(destroy);

watch(() => props, () => {
    init();
}, { deep: true });
</script>

<template>
    <div ref="containerRef" :class="props.classNameWrapper"></div>
</template>

// home/src/components/core/Galleries/GalleryClothes/GalleryClothes.tsx
import React, { useRef, useEffect } from "react";

import {
  mountComponent,
  MountOptions,
  unMountComponent,
} from "shared_react/SharedReact";
import { Component } from "shared_react/SharedReactEnums";
import { GalleryClothesProps } from "shared_react/SharedReactProps";

export const GalleryClothes = ({
  idRoot,
  children,
  clothes,
  title,
  language,
  className,
  classNameWrapper,
  onClothesClick,
}: GalleryClothesProps) => {
  const ref = useRef<HTMLDivElement | null>(null);

  const onInit = () => {
    const options: MountOptions = {
      idComponent: Component.LoaderScreen,
      props: {
        idRoot: idRoot,
        children: children,
        title: title,
        language: language,
        className: className,
        clothes: clothes,
        onClothesClick: onClothesClick,
      },
    };

    mountComponent(ref.current!, options);
  };

  const onClothesChange = () => {
    const options: MountOptions = {
      idComponent: Component.GalleryClothes,
      props: {
        idRoot: idRoot,
        children: children,
        title: title,
        language: language,
        className: className,
        clothes: clothes,
        onClothesClick: onClothesClick,
      },
    };

    mountComponent(ref.current!, options);
  };

  const onDestroy = () => {
    unMountComponent(idRoot);
  };

  useEffect(() => {
    onInit();

    return () => {
      onDestroy();
    };
  }, []);

  useEffect(onClothesChange, [clothes]);

  return <div ref={ref} className={classNameWrapper}></div>;
};
