// product_detail/src/components/core/Images/ImageWithBackgroundColor/ImageWithBackgroundColor.vue
<script setup lang="ts">
import { defineProps, ref, onMounted, onBeforeUnmount, watch } from "vue";

import { mountComponent, unMountComponent } from "shared_core/SharedCore";
import { ImageWithBackgroundColorProps } from "shared_core/SharedCoreProps";
import { Component } from "shared_core/SharedCoreEnums";
import { MountOptions } from "shared_core/SharedCoreEntities";

const props = defineProps<ImageWithBackgroundColorProps>();

const containerRef = ref<HTMLDivElement | null>(null);

function init() {
    if (!containerRef.value) return;

    const options: MountOptions = {
        idComponent: Component.ImageWithBackgroundColor,
        props: {
            idRoot: props.idRoot,
            src: props.src,
            alt: props.alt,
            bgColor: props.bgColor,
            isActive: props.isActive,
            language: props.language,
            className: props.className,
            onClick: props.onClick,
        }
    };

    mountComponent(containerRef.value, options);
}

function destroy() {
    unMountComponent(props.idRoot);
}

onMounted(init);
onBeforeUnmount(destroy);

watch(() => props, () => {
    init();
}, { deep: true });
</script>

<template>
    <div ref="containerRef" :class="props.classNameWrapper"></div>
</template>

// shared_react/src/components/core/Images/ImageWithBackgroundColor/ImageWithBackgroundColor.tsx
import React, { useEffect, useRef } from "react";

import { mountComponent, unMountComponent } from "shared_core/SharedCore";
import { ImageWithBackgroundColorProps } from "shared_core/SharedCoreProps";
import { Component } from "shared_core/SharedCoreEnums";
import { MountOptions } from "shared_core/SharedCoreEntities";

export const ImageWithBackgroundColor = ({
  idRoot,
  src,
  alt,
  bgColor,
  isActive,
  language,
  onClick,
  className,
  classNameWrapper,
}: ImageWithBackgroundColorProps) => {
  const ref = useRef<HTMLDivElement | null>(null);

  const onInit = () => {
    const options: MountOptions = {
      idComponent: Component.ImageWithBackgroundColor,
      props: {
        idRoot: idRoot,
        src: src,
        alt: alt,
        bgColor: bgColor,
        isActive: isActive,
        language: language,
        className: className,
        onClick: onClick,
      },
    };

    mountComponent(ref.current!, options);
  };

  const onDestroy = () => {
    unMountComponent(idRoot);
  };

  useEffect(() => {
    onInit();

    return () => {
      onDestroy();
    };
  }, []);

  return <div ref={ref} className={classNameWrapper}></div>;
};
